// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1G8LTx_Ul4HCQ1CUgyEenfkkDkOVH3tw',
    appId: '1:935431827512:web:2d988747233475bdad36cd',
    messagingSenderId: '935431827512',
    projectId: 'tesfood-app',
    authDomain: 'tesfood-app.firebaseapp.com',
    storageBucket: 'tesfood-app.appspot.com',
    measurementId: 'G-GLJHLTDZ1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHt35GAHWYaEr1DEylUj8r96JaSYnzCok',
    appId: '1:935431827512:android:61175c3b1c6d93b7ad36cd',
    messagingSenderId: '935431827512',
    projectId: 'tesfood-app',
    storageBucket: 'tesfood-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw8CMnAOEysyXL5X_-YZVAze7dPU7LxjE',
    appId: '1:935431827512:ios:680635fedb85f297ad36cd',
    messagingSenderId: '935431827512',
    projectId: 'tesfood-app',
    storageBucket: 'tesfood-app.appspot.com',
    iosBundleId: 'com.example.mealeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw8CMnAOEysyXL5X_-YZVAze7dPU7LxjE',
    appId: '1:935431827512:ios:680635fedb85f297ad36cd',
    messagingSenderId: '935431827512',
    projectId: 'tesfood-app',
    storageBucket: 'tesfood-app.appspot.com',
    iosBundleId: 'com.example.mealeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1G8LTx_Ul4HCQ1CUgyEenfkkDkOVH3tw',
    appId: '1:935431827512:web:11a99bc982153ac6ad36cd',
    messagingSenderId: '935431827512',
    projectId: 'tesfood-app',
    authDomain: 'tesfood-app.firebaseapp.com',
    storageBucket: 'tesfood-app.appspot.com',
    measurementId: 'G-TGKRPM1V9W',
  );
}
